FROM python:3.10-slim

# Системные зависимости
RUN apt-get update && apt-get install -y \
    gcc \
    ffmpeg \
    libsndfile1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app


# Установка PyTorch (CPU-only) и зависимостей проекта
RUN pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "v1.main:app", "--host", "0.0.0.0", "--port", "8000"]